name: Build Wheel using Hatch

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build --target hatch -t myapp:hatch .
    - name: Build wheel with build module
      run: docker run --rm -v "${{ github.workspace }}:/app" myapp:hatch build
    - name: Copy wheel to host
      run: docker cp $(docker create --rm myapp:hatch):/app/dist ./
    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/*.whl
