name: PyLint with Black

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build --target dev -t myapp:dev .
    - name: Format code with Black
      run: docker run --rm -v "${{ github.workspace }}:/app" myapp:dev black --check --diff .
    - name: Analyzing the code with pylint
      run: docker run --rm -v "${{ github.workspace }}:/app" myapp:dev pylint $(git ls-files '*.py')
